---
title: "overdispersion simulations"
author: "Michel de Lange"
date: "5/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CI's



```{r echo=F}
source('~/Documents/overdispersion/readresults2.R')

# This csv file contains 24 columns:
#   6 coverage rates.  
#   6 proportions with phi.lower > 1
#   6 median widths of the CI for phi
#   6 rates of method not working.
#   a further 2 columns have been added for mu.lower and mu.upper

#results$mu.lower <- round(results$mu.lower,1)
#results$mu.upper <- round(results$mu.upper,1)
#results$cov.chisq <- round(results$cov.chisq,2)
#results$cov.gamma <- round(results$cov.gamma,2)
#results$cov.boots1 <- round(results$cov.boots1,2)
#results$cov.boots2 <- round(results$cov.boots2,2)
#results$cov.vgam <- round(results$cov.vgam,2)
#results$cov.ee <- round(results$cov.ee,2)


# where phi==1, population is Poisson
results[which(results$phi==1),"Population"] <- "Poisson"
#results.ordered <- 
#  results[order(results$Population,
#                results$phi,
#                results$n,
#                results$mu.lower),]


```

```{r }
library(knitr)
kable(results[,c(1,2,3,31,32,7:12)],
      caption='Coverage of 90% CIs',
      digits=2)
```

```{r }
kable(results[,c(1,2,3,31,32,13:18)],
      caption='lower bound 90% CIs exceeds 1 (proportion)',
      digits=2)
```

```{r }
kable(results[,c(1,2,3,31,32,19:24)],
      caption='90% CIs median width',
      digits=2)

```

```{r }
kable(results[,c(1,2,3,31,32,25:30)],
      caption='Proportion of times method does not work',
    digits=2)
```


