---
title: "overdispersion simulations"
author: "Michel de Lange"
date: "22/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CI's

The bootstrap has now been calculated by bootstrapping the residuals.





```{r echo=F}
##
##  This program prints tables of the CI's of beta.
##
results <- NA
setwd('~/Documents/overdispersion/nesi')
source('readResults11.R')
# colnames(results)

# This csv file contains 20 columns:
#   Population, phi, n, b1, b2, N  (that is 6)
#   3 coverage rates.  
#   3 proportions with CI not containing zero
#   3 median widths of the CI for phi
#   3 rates of method not working.
#   mu.lower and mu.upper

 

# where phi==1, population is Poisson
results[which(results$phi == 1),"Population"] <- "Poisson"
 

```

```{r }
library(knitr)
header.cols <- c(1,3,4,5,14,15,2)
kable(results[,c(header.cols,7,8)],
      caption='Coverage of 95% CIs',
      digits=2)
```

```{r }
kable(results[,c(header.cols,9,10)],
      caption='CI for beta/phi excludes zero/1 ',
      digits=2)
```

```{r }
kable(results[,c(header.cols,11,12)],
      caption = '90% CIs median width',
      digits = 2)
```

```{r }
kable(results[,c(header.cols,13)],
      caption = 'Proportion of times method does not work',
    digits = 2)
```


